### PR TITLE
A definition of the monads focusing on the side-effects

### PR DESCRIPTION
**Pull request by clarus**
Indeed, I believe that the representation of side-effects is what the monads are the most used for.

### CODE REVIEW

**Comment by jethrolarson** [comment]
This makes monads seem more confusing than the original. We're also using the fantasy-land terms by default. There's discussion about adding a wiki to this repo that would go into more detail on some of the more academic terms. Promise .then isn't the same ad the monad bind

**Comment by clarus** [comment]
> There's discussion about adding a wiki to this repo that would go into more detail on some of the more academic terms.

:+1: 

> Promise .then isn't the same ad the monad bind

I am curious, why do you think the `.then` and the `bind` are not the same?

**Comment by clarus** [comment]
In any cases, I think a description of the monads should talk about the side-effects, since that what the monads are the most used for (from what I have seen).

**Comment by puffnfresh** [comment]
If I have an array of numbers, I wouldn't say that arrays are about numbers. Similarly, I wouldn't say monads are about side-effects.

:-1:

**Comment by puffnfresh** [comment]
Coincidentally arrays are monadic and have nothing to do with side-effects.

**Comment by jethrolarson** [comment]
`.then` has a different api. It can act like `bind` if the passed function returns a promise, but it doesn't do so for all values. It's also a binary method with an optional second parameter. In short it doesn't follow the rules well enough.

**Comment by hemanth** [comment]
`.then` and the `bind` aren't the same.

> There's discussion about adding a wiki to this repo that would go into more detail on some of the more academic terms.

I guess, we must request more humans to join hands on this?

**Comment by clarus** [comment]
> .then has a different api. It can act like bind if the passed function returns a promise, but it doesn't do so for all values.

Yes, the `.then` is more permissive than `bind`, but to me this is in the same way than the `+` operator doing implicit conversions on its arguments in JavaScript. Basically, the type of `.then` is:

```
(this: Promise<A>,  handler: (A -> Promise<B>)) -> Promise<B>
```

and other variants can be deduced from it.

> It's also a binary method with an optional second parameter.

This is just about syntax, no?

> If I have an array of numbers, I wouldn't say that arrays are about numbers. Similarly, I wouldn't say monads are about side-effects.

Yes, technically monads are not *only* about side-effects, but I think this is important to mention it since (to me) that is what they are the most used for. A presentation I like about monads: http://gallium.inria.fr/~xleroy/mpri/2-4/monads.2up.pdf

> Coincidentally arrays are monadic and have nothing to do with side-effects.

The array monad can be related to side-effects as that it is the representation of the non-derminism effect.

**Comment by clarus** [comment]
To put it in a fun way, saying that monads are not about side-effects is like saying that keys are not about unlocking a door, since you can also use it to open your beer.

**Comment by jethrolarson** [comment]
Saying monads are about side effects is like saying that screwdrivers are about picture frame hanging. Sure you may use a screw driver for that, but it's just a tool

**Comment by clarus** [comment]
As an introduction to functional programming, I think it is important to present realistic use cases. AFAIK, monads arrived in programming to handle side effects in Haskell. I have not encountered many other use cases, even if as you said it is just a tool so it is possible. But I do not see much constructive discussions in this thread. Still curious to understand why you do not classify promises as a monad though.

**Comment by jethrolarson** [comment]
To say something is a monad is to say it satisfies the monad laws. If it
does, it's a monad; if it doesn't, it's not. I don't think .then satisfies
them quite correctly. Promise can be made into a monad easily though

**Comment by clarus** [comment]
> To say something is a monad is to say it satisfies the monad laws. If it does, it's a monad.

Obviously.

> I don't think .then satisfies them quite correctly.

To assert something, you should to be able to provide clear explanations of why. Else the effect may be the opposite, and could be interpreted as a lack of background? I do not see in this thread any explanations other than "that is what I think", thus closing this thread.

**Pull request closed without merging**
