### PR TITLE
Remove blockquotes

### PR DESCRIPTION
**Pull request by jethrolarson**

### CODE REVIEW

**Comment by hemanth** [comment]
Rebase bro!

**Comment by jethrolarson** [comment]
They're all separate changes. You want to squash them?

**Comment by hemanth** [comment]
Better 👍

**Comment by denisbalyko** [comment]
But what about the agreement?
https://github.com/hemanth/functional-programming-jargon/blame/master/contributing.md#L20

**Comment by jethrolarson** [comment]
I just wrote that styleguide. What's the discrepancy?

**Comment by denisbalyko** [comment]
> Parenthesis around function arguments

Need to keep the brackets for a single argument or not?

**Comment by jethrolarson** [comment]
Git got mucked up. Going to reopen with a different branch

**Pull request closed without merging**
