### PR TITLE
adding `bind` and `return` note to Monad entry

### PR DESCRIPTION
**Pull request by ethagnawl**

### CODE REVIEW

**Comment by stoeffel** [comment]
Maybe it should be mentioned that `bind` and `return` isn't fantasyland conform. Otherwise this looks good.

**Comment by ethagnawl** [comment]
That seems reasonable. Any suggestions on verbiage?

**Comment by stoeffel** [comment]
Maybe add something like "`return` and `bind` aren't fantasyland conform ([see monad spec](https://github.com/fantasyland/fantasy-land#monad)" at the end.

**Comment by ethagnawl** [comment]
OK - I added something to that effect. It might also be worth adding a note at the top-level which explains that these examples aim to conform to the Fantasy Land spec.

**Comment by stoeffel** [comment]
:+1: and maybe a section to describe what fantasyland is would be great.

**Comment by ethagnawl** [comment]
Cool - I'll create a separate issue for that.

**Comment by jethrolarson** [comment]
It's getting a little long.

**Comment by stoeffel** [comment]
If we add a fl section we can just state (not fantasyland compatible) and link to that section. and maybe we could add generally links to the spec, where a spec exists (after the title or in a small footnote)

**Comment by hemanth** [comment]
A :+1: for the footnote.

**Comment by stoeffel** [comment]
I will create a PR as soon as I got time and nobody is quicker ;-)

**Comment by ethagnawl** [comment]
@jethrolarson I just shortened the note up a bit.

**Comment by hemanth** [comment]
:+1:

**Comment by Xe** [comment]
Why does `Monad` define `return` here? `pure` as a part of `Applicative` does everything `return` does.

**Pull request merged**
