### PR TITLE
In-depth proofreading and correcting

### PR DESCRIPTION
**Pull request by noplanman**
First off, this was very interesting to read and learn from, **huge thanks to all contributors**!!

There are quite a lot of changes, so please let me know which ones don't make sense to you and I'll revert them.
I've tried to make all the explanations and their respective code examples as "pretty" and consistent as possible.

Here's a list of what this PR contains:
- Typo, missing word and duplicate word corrections.
- Method names at the beginning of a sentence aren't capitalised (e.g. "`ap` applies a function in the object...")
- Give code snippets some space (1 empty line before and 1 after).
- All code snippets are now syntax highlighted with JS.
- Whitespaces in code snippets corrected.

Some suggestions / questions:
- Maybe have a TOC? (table of contents)
- Semicolons (everywhere vs. nowhere vs. here-and-there):
  Some code snippets have them, others don't, others have a combination.

### CODE REVIEW

**Comment by hemanth** [comment]
Wow! Thanks for this.

`TOC` would be very useful.

I would vote for `semicolons` everywhere.

Let me bring in some more experts here:

//cc @jethrolarson @CrossEye @stoeffel 

Without the wonderful contributions like this, this repo would be meaning less.

**Comment by jethrolarson** [comment]
I personally have left semi-colons behind but they are part of typical idiomatic js so I understand using them here

**Comment by jethrolarson** [comment]
I didn't notice any problem with the diff. :sheep:

**Comment by stoeffel** [comment]
LGTM 🐢

**Comment by hemanth** [comment]
@noplanman Thanks, merged! Any ideas on the `TOC` ? 👼

**Comment by stoeffel** [comment]
@hemanth here you go #39

**Comment by noplanman** [comment]
Regarding the semi-colons, shall I do something about them or would you prefer to leave the examples as they are for now?

**Comment by jethrolarson** [comment]
Add them if you're inclined

**Comment by jethrolarson** [comment]
Parens around unary arrow function params?

**Comment by noplanman** [comment]
I'm no JS expert, so I'd really appreciate some guidance from you guys.
Does it make sense to have semi-colons?
And the parenthesis around the function params?

I'm all for good coding style practices, just need to learn them from pros :wink:

It's basically you guys suggesting what could be improved and I'll learn it by doing.
Is that ok?

**Pull request merged**
