### PR TITLE
Add more Functional Programming Libraries in JavaScript

### PR DESCRIPTION
**Pull request by stereobooster**

### CODE REVIEW

**Comment by stereobooster** [comment]
There are also [mori](https://github.com/swannodette/mori) and [Immutable.js](https://facebook.github.io/immutable-js/).

**Comment by jethrolarson** [comment]
If this gets exhaustive then it'll be too big for this document. Maybe we should move the list to the wiki

**Comment by stereobooster** [comment]
https://github.com/hemanth/functional-programming-jargon/wiki/Other-resources ?

**Comment by jethrolarson** [comment]
We could add a link to the wiki list to the readme and remove the existing list

**Pull request closed without merging**
