### PR TITLE
Added Guard definition

### LINKED ISSUE #31: Add definition for Guarded Function
Willing to assign myself to this one as it's probably one of most straightforward concepts of functional programming.

### PR DESCRIPTION
**Pull request by IcarianComplex**
Fixes #31

### CODE REVIEW

**Comment by hemanth** [comment]
Yeah, `JS` example would be useful.

**Comment by jethrolarson** [comment]
@hemanth I notice that there's no text that says that this document is only in JavaScript. Should we be limiting the list of terminology to concepts that are accomplishable in js?

**Comment by hemanth** [comment]
No limitations as such, but it's been `JS` so far, I would like to hear what @IcarianComplex has to say.

**Comment by IcarianComplex** [comment]
Only way to do it in JS would be to use `if/else` statements (as far as I know). Thing is I've never heard of people referring to `if/else` statements as guards which leads me to wonder if they're not entirely interchangeable. My language theory professor was uncertain too, but he did mention that programming languages already had the conditional `if/else` mechanism long before the term guard was first coined. 

On the other hand, I haven't encountered any code written with guards that can't be rewritten with `if/else` statements so perhaps the difference is purely syntactical. 

Let me know what your thoughts are.

**Comment by jethrolarson** [comment]
You can use composition with predicates and maybe `Maybe` to do something
similar I guess. Are guards compile-time or runtime?

**Comment by jethrolarson** [comment]
I think we can close this in favor of #53.

**Pull request closed without merging**
