### PR TITLE
Added functor laws and example to the functor section

### PR DESCRIPTION
**Pull request by matthieubulte**

### CODE REVIEW

**Comment by stoeffel** [comment]
Shouldn't we just link to fantasy-land for the laws? It will blow up all this short descriptions if we start adding all the laws and may be inaccurate or not uptodate with fl.
Was meaning to create a PR to link to all the laws, but was too busy.

**Comment by matthieubulte** [comment]
I'm also for linking to some other place, but I was not sure what kind of extra resources are at the right level.
The laws are accurate and don't change, as for the conciseness, I created this PR to have the minimal correct description after reading a tweet pointing the danger of oversimplification.

I'll create another PR for monads and we can discuss more before merging if it's the right approach :)

**Comment by stoeffel** [comment]
Jop, the laws are accurate, but can easily diverge (with the fl-spec) for
more complicated types. IMO they are not needed to explain what a
functor/or other types are. I think it's best to link to the specification
of https://github.com/fantasyland/fantasy-land for this.

**Comment by matthieubulte** [comment]
The laws won't diverge, really. These are not concepts that fl are making up or that we're redefining, they are established concepts that we just want to describe in an approachable way for the JS community.

FL is doing a very good job in describing in a terce way all of the typical algebraic structures found in FP, but for this repo to be useful, I think it should really offer more than concise explanations.

Maybe other of the maintainers of this repo can share their opinion here.

**Comment by jethrolarson** [comment]
Initially I was opposed to diving into the laws, but this case isn't too confusing to me. Could be another case for a linked wiki for depth on the terms rather than fully explaining in the main document

**Pull request merged**
