### PR TITLE
Don't reinvent Array.prototype.flatMap

### PR DESCRIPTION
**Pull request by theqp**

### CODE REVIEW

**Comment by CrossEye** [comment]
The point is that `chain` is available to *any* monad.  It's part of the JS version of a Monad specification.  That there's a shortcut for arrays is useful to know and good to point out, but we can't just say, "Oh, for arrays, use the `flatMap` method instead."  We can't special-case generic implementations for arrays.

We could simply write `Array.prototype.chain = Array.prototype.flatMap`, but I would rather do that as a comment about an alternative after demonstrating the behavior that's already there.

**Comment by theqp** [comment]
@CrossEye 
I have restored `chain`.
> I would rather do that as a comment about an alternative after demonstrating the behavior that's already there.

I am not sure what you meant by that. Having both an implementation with `reduce` and an alternative that shows ES2019 has flatMap?

**Comment by jethrolarson** [comment]
Another consideration is that the type signature, while compatible a lot of the time, isn't the same. 

Thankfully its closer than Promise.then

**Comment by jethrolarson** [comment]
While there may be better code to be used I don't think we should take this change. The point it to show how it works and a simple assignment doesn't show that.

**Pull request closed without merging**
