### PR TITLE
Typo Fixes

### PR DESCRIPTION
**Pull request by hycner**
- Remove unnecessary semicolons in Functor example
- Fix "map" typo in Lift example

### CODE REVIEW

**Comment by hycner** [comment]
Welp, nevermind then. Are the leading semicolons intentional as well? I've noticed a few more around the repo

**Comment by hemanth** [comment]
>Are the leading semicolons intentional as well?

^ Not really, let us clean them for now, thanks for the PR.

**Comment by jethrolarson** [comment]
We're using the javascript standard style which skips semicolons. Run npm
test to see the error output

**Comment by jethrolarson** [comment]
Leading semicolons are necessary when you start a line with an array
literal if you're omitting the trailing ones

**Comment by dodekeract** [comment]
@jethrolarson What about integrating Travis CI with this project? It's free for open source and would show that the tests failed. :smile:

**Comment by hycner** [comment]
Cool thanks, all! Closing in lieu of info above

**Pull request closed without merging**
