### PR TITLE
Edit and expand Arity, Lazy Evaluation, and Monad definitions

### PR DESCRIPTION
**Pull request by sjsyrek**
I expanded the definitions of Arity, Lazy evaluation, and Monad. I may be able to do more, as I think this is a worthwhile project, but I want to make sure I’m not being too verbose. I’m still learning these concepts myself and find that trying to explain them is a good way of doing so!

### CODE REVIEW

**Comment by hemanth** [comment]
:+1: thanks!

**Comment by sjsyrek** [comment]
First pull request ever!

**Comment by stoeffel** [comment]
@sjsyrek Nice work :fireworks:

**Comment by hemanth** [comment]
WOW! Congrats @sjsyrek.

**Pull request merged**
