### PR TITLE
Continuations

### LINKED ISSUE #128: Continuations
How do we feel about adding _continuations_ to this list? Especially in FP with JavaScript, continuations are pretty important and can be confusing to understand for beginners without having a simple definition to reference.

If we want to add continuations, I can submit a PR for this!

### PR DESCRIPTION
**Pull request by nickzuber**
Added continuations with a short definition and example, and also added a brief commentary and example on how continuations are relevant in JavaScript async programming.

Closes #128

### CODE REVIEW

**Comment by jethrolarson** [comment]
Thanks for tackling this it looks pretty good. "Collection of instructions" sounds like it could mean something else though. Does my suggestion above make sense?

**Comment by nickzuber** [comment]
@jethrolarson Maybe we can change the wording to "collection of steps" or something — unless you had something else in mind? I personally had the light bulb moment with continuations when I realized they were just the remaining steps in a program, so my wording here might be bias

**Comment by hemanth** [comment]
> "collection of steps"

Block of code?

**Comment by nickzuber** [comment]
@hemanth Yeah I think using "code" makes things more clear — how does this revision sound:

> At any given point in a program, the remaining code that still needs to be completed is known as a continuation.

or 

> At any given point in a program, the code that still needs to be completed is known as a continuation.

**Comment by hemanth** [comment]
> At any given point in a program, the part of the code that's yet to be executed is known as a continuation.

^ ?

**Comment by nickzuber** [comment]
@hemanth LGTM 👍

**Pull request merged**
