### PR TITLE
typo in Lift example code

### PR DESCRIPTION
**Pull request by Fetz**

### CODE REVIEW

**Comment by hemanth** [comment]
🍍

**Comment by Fetz** [comment]
oh I see, but you only talk about it, later in Applicative Functor, maybe changing the order of Lift?

**Comment by jethrolarson** [comment]
Maybe, though there's been people pushing to alphabetize the page so I
think the definitions should stand on their own if possible

**Comment by dodekeract** [comment]
I think this definitely needs a comment. It just looks far too much like a typo.

**Comment by hemanth** [comment]
[Done](https://github.com/hemanth/functional-programming-jargon/blob/master/readme.md#lift)

**Pull request closed without merging**
