### PR TITLE
Write a more complete introduction.

### PR DESCRIPTION
**Pull request by PaulBone**
This introduction introduces why this glossary is important and that the
examples are in JavaScript syntax.

### CODE REVIEW

**Comment by jethrolarson** [comment]
:+1:

**Comment by BobWhitelock** [comment]
Looks good - maybe also mentioning that it's JavaScript using lots of ES2015 syntax would be useful, since it's not universal yet?

**Comment by hemanth** [comment]
art-artist-on-tumblr-delirium-lab-3oEduRygZtVxloohws

**Comment by Alhadis** [comment]
JavaScript is like the English of programming. Everybody knows it, and is expected to know at least the basics, heh.

Good work!

**Comment by PaulBone** [comment]
Thanks.

I'm afraid I don't know this English of Programming. ;-) My English of Programming is C.

**Comment by Alhadis** [comment]
Damn it, I should've said "web programming" or something less insulting. Sorry. :(

(BTW, you're not missing out on much... I can guarantee you'd pick it up in no time. It's probably the easiest language in the world to learn. >_>)

**Comment by PaulBone** [comment]
No need to apologise, I didn't feel insulted.

**Pull request merged**
