### PR TITLE
Sorted

### PR DESCRIPTION
**Pull request by AlexScheller**
Not sure if you all are interested in this but some dude on reddit made a comment about how the readme.md isn't alphabetized so I wrote a little script to sort the relevant sections of the readme.md without ruining the markdown. It relies on the format not changing too much, but it works. I've also run it on the readme.md file so I'm submitting the alphabetized version of that too. The intent is that people contributing examples wouldn't need to worry about hand alphabetizing in the future. I'm up for making it more robust, better commented and cleaner if it gets picked up.

### CODE REVIEW

**Comment by jethrolarson** [comment]
I'm not 100% sure it should be alphabetized. What's the reddit thread?

**Comment by jethrolarson** [comment]
Also you shouldn't have to alphabetize the TOC, just regenerate the TOC after sorting the rest

**Comment by AlexScheller** [comment]
https://www.reddit.com/r/programming/comments/4u9c3a/functional_programming_jargon_defined_in_plain/

Yeah if it doesn't need to be alphabetized or some other structure is preferred that's fine. It was just one comment in the thread, but I had time to write something up. About generating the TOC, is that a function of the markdown itself, or did you mean rewrite the progeram to generate it rather than sort the static list?

**Comment by jethrolarson** [comment]
There's a script in the package.json `npm run toc` or something like that

**Comment by hemanth** [comment]
@AlexScheller Currently we are using [roadmarks](https://www.npmjs.com/package/roadmarks), feel free to change as per the need, thanks!

**Comment by AlexScheller** [comment]
Oh can't believe I missed that thanks.

**Comment by clarus** [comment]
:+1: for sorting! It feels easier to me when I want to go back to some definition I have already seen. Also, maybe adding (and then maintaining) a script for sorting is overkill compared to enforcing this convention for new contributions.

**Comment by hemanth** [comment]
> enforcing this convention for new contributions.

Would be an over head for the contributors.

Better to have a post commit hook to sort!

**Comment by galtenberg** [comment]
👎 for sorting - I'd recommend, in fact, to order the README from simpler concepts to more complex concepts, since the goal of the repo as stated is `we hope to make learning FP easier`. 

(Being a tutorial over being a strict glossary.)

Maybe a secondary section could have an alphabetized list of the concepts.

Thanks for all the great work! Really eye opening.

**Comment by jethrolarson** [comment]
That's always been my preference

**Pull request closed without merging**
