### PR TITLE
Made an accurate translation Russian 

### PR DESCRIPTION
**Pull request by thinkjazz**
Made an accurate translation in Russian can also do in Ukrainian, if necessary

### CODE REVIEW

**Comment by Masynchin** [comment]
Зачем круглики поменяны на тире?

~~~diff
- `f • (g • h)` is the same as `(f • g) • h`
+ `f - (g - h)` то же самое, что `(f - g) - h`
~~~

**Comment by thinkjazz** [comment]
Наверное, потерял при ctrl+c \ ctrl+v

**Comment by hemanth** [comment]
This should be an independent file or repo, we can't overwrite the default readme.

**Comment by thinkjazz** [comment]
sure) I'll 

> ```diff
> то же самое
> ```
Пыщь) добрался исправил

**Comment by thinkjazz** [comment]
> This should be an independent file or repo, we can't overwrite the default readme.

I fixed some typos and make ref to russian haskell translation
Here translation your document
https://github.com/thinkjazz/functional-programming-jargon/blob/master/readme.md

**Pull request closed without merging**
