### PR TITLE
"homomorphism" definition from simpleWikipedia

### PR DESCRIPTION
**Pull request by josusanmartin**
The homomorphism definition was a bit confusing. This one seems better: https://simple.wikipedia.org/wiki/Homomorphism

### CODE REVIEW

**Comment by jethrolarson** [comment]
We can't steal that text without satisfying the license associated with the source.

**Comment by hemanth** [comment]
The current definition in our repo reads as:

> A homomorphism is just a structure preserving map. In fact, a functor is just a homomorphism between categories as it preserves the original category's structure under the mapping.

Maybe we should hyperlink `functor`, `categories`? 

Also instead of just defining morphism as: `A transformation function.` We can add few more lines of description?

**Comment by jethrolarson** [comment]
I think both the old definition of homomorphism and the simple wiki definition are unapproachable. 

What's a structure-preserving map? And the example includes functions that aren't defined anywhere. I'm taking a whack at rewriting this. Problem is I don't really understand how a homomorphism is different from a natural transformation or isomorphism so time to study :)

**Comment by jethrolarson** [comment]
I think this PR is superceded by #228

**Pull request closed without merging**
